Add ignored and excluded classes to critical CSS extraction in `collect`
callstack/linaria pull request #1102
Opened 2022-10-25 15:58 UTC by ezlie-nguyen

## Motivation

Our codebase uses the [postcss-rtlcss](https://www.npmjs.com/package/postcss-rtlcss) package to add `.dir-ltr`, `.dir-rtl`, or `.dir` prefixes to our CSS selectors, so that most of them are in the following format:
```
.dir-ltr.otherClassname {
   padding-bottom: 12px;
}
```

Since our HTML contains the `dir-ltr` class, when we use Linaria's `collect` function, a lot of unnecessary selectors are added to the critical CSS even though `otherClassname` is not present.

Also, we have media queries in this format:
```
@media(...) {
  .dir-ltr.otherClassname {
    padding-left: 12px;
  }
  .dir-rtl.otherClassname {
    padding-right: 12px;
  }
}
```

We want to specifically exclude the RTL selector when the direction is LTR and vice versa.

## Summary

This PR proposes to add an opt-in `ignoredClasses` parameter to `collect` so that we can ignore `dir-ltr`, `dir-rtl`, and `dir` from the regex used to determine critical CSS styles when it is present in the HTML.

Also, the `excludedClasses` parameter will allow `dir-rtl` to be excluded, so that even if `otherClassname` is in the HTML, the `.dir-rtl.otherClassname` selector will not be critical.

## Test plan

Tested with unit tests for the new parameters to the `collect` function.

2022-10-26 06:12 UTC, Anber requested changes
It looks good to me.
Could you please run `pnpm changeset` and describe your changes?

2022-10-26 18:03 UTC, ezlie-nguyen commented
> It looks good to me. Could you please run `pnpm changeset` and describe your changes?

@Anber added! Thanks for the review 🙂

2022-11-04 20:27 UTC, lencioni commented on packages/server/src/collect.ts
> +        removedNodesFromOther++;
I think you can avoid disabling eslint here like this:
```suggestion
        removedNodesFromOther += 1;
```

2022-11-04 20:27 UTC, lencioni commented on packages/server/src/collect.ts
> +  const excludedClassesRegExp = new RegExp(excludedClasses.join('|'), 'gm');
Probably a good idea to escape the excludedClasses array for special regex characters.

2022-11-04 20:27 UTC, lencioni commented on packages/server/src/collect.ts
> +      if (className !== '' && !ignoredClasses.includes(className)) {
Since this is run in a couple of loops, it might not be a bad idea to convert `ignoredClasses` to a Set outside of the loops for performance.

2022-11-07 16:06 UTC, ezlie-nguyen commented
@lencioni I think I addressed your comments, mind taking another look?

2022-11-07 21:58 UTC, lencioni commented on packages/server/src/collect.ts
> +}
I'm curious about the regex here. Did you write this by hand or pull it from somewhere?

It might be worth borrowing lodash's implementation. https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L14259-L14279

Here's their regex, which looks a little bit different than the one in this PR: https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L152

Their code comment points to https://262.ecma-international.org/7.0/#sec-patterns as the data source for this list of characters (though that inline link didn't work for me maybe it is supposed to be this one? https://262.ecma-international.org/7.0/#sec-regular-expressions-patterns)

2022-11-07 22:15 UTC, jpnelson approved these changes

2022-11-07 22:15 UTC, jpnelson commented on packages/server/src/collect.ts
> +  excludedClasses: string[] = []
For naming, to me, `ignored` and `excluded` are synonyms, so I have a hard time remembering which one is doing which. Is there some other name I'm not thinking of that would help clarify what these do?

2022-11-07 23:24 UTC, jpnelson commented on packages/server/src/collect.ts
> +}
Would you consider also not using regex to do the string matching, and just doing string searching? (ie, `indexOf`)

2022-11-09 22:26 UTC, ezlie-nguyen commented on packages/server/src/collect.ts
> +  excludedClasses: string[] = []
Yeah I agree the naming for this is tricky. What do you think about `ignoredClasses` and `blockedClasses`?

2022-11-10 16:54 UTC, ezlie-nguyen commented on packages/server/src/collect.ts
> +}
I'm not quite following what the string searching would look like? Won't we still have to call `string.replace` to sanitize it?

re: the regex, I pulled it from somewhere, but happy to replace it with the one from lodash.

2022-11-19 12:28 UTC, Anber approved these changes

2022-11-19 12:29 UTC, Anber commented on packages/server/src/collect.ts
> +  excludedClasses: string[] = []
What's about this thread? Are you going to change names or I can merge this PR?

2022-12-17 00:33 UTC, ezlie-nguyen commented on packages/server/src/collect.ts
> +  excludedClasses: string[] = []
Sorry for the delay, I changed the param names and this should be good to go now!

2022-12-20 16:07 UTC, merged